[package]
name = "rust-matchmaking-server"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
warp = { version = "0.3.7", features = ["tls"] }
